  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-ide-deployment
    namespace: part-rde
    labels:
      app: frontend-ide
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: frontend-ide
    template:
      metadata:
        annotations: 
            update: 8a94b5506bdc3b41295f41a847408f71
        labels:
          app: frontend-ide
      spec:
        containers:
          - name: frontend-ide
            image: amdp-registry.skamdp.org/mydev-ywyi/frontend-ide:IDE.1.0.4
            imagePullPolicy: Always


