apiVersion: v1
kind: Service
metadata:
  name: frontend-ide-service
  namespace: part-rde
spec:
  selector:
    app: frontend-ide
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8888
  type: ClusterIP

